
import React from 'react';
import { CheckCircle2, XCircle, AlertCircle, FileText, Share2, Printer, ArrowLeft, Lightbulb } from 'lucide-react';
import { DecisionResult, LoanApplication } from '../types';

interface DecisionViewProps {
  application: LoanApplication;
  onReset: () => void;
}

const DecisionView: React.FC<DecisionViewProps> = ({ application, onReset }) => {
  const isApproved = application.analysis.status === DecisionResult.APPROVED;
  const isRejected = application.analysis.status === DecisionResult.REJECTED;
  const isFraud = application.analysis.status === DecisionResult.FRAUD;

  const config = {
    [DecisionResult.APPROVED]: {
      icon: CheckCircle2,
      color: 'bg-emerald-600',
      text: 'Loan Application Approved',
      textColor: 'text-emerald-900',
      subText: 'The application meets all bank risk requirements.'
    },
    [DecisionResult.REJECTED]: {
      icon: XCircle,
      color: 'bg-red-600',
      text: 'Loan Application Rejected',
      textColor: 'text-red-900',
      subText: 'Profile did not meet the required solvency or scoring benchmarks.'
    },
    [DecisionResult.FRAUD]: {
      icon: AlertCircle,
      color: 'bg-orange-600',
      text: 'Potential Fraud Detected',
      textColor: 'text-orange-900',
      subText: 'Critical anomalies detected in the provided documentation.'
    },
    [DecisionResult.PENDING]: {
      icon: AlertCircle,
      color: 'bg-gray-600',
      text: 'Pending Manual Review',
      textColor: 'text-gray-900',
      subText: 'Requires human intervention.'
    }
  }[application.analysis.status];

  const Icon = config.icon;

  return (
    <div className="max-w-5xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-1000">
      <div className="text-center">
        <h2 className="text-3xl font-bold text-gray-900 mb-2">Layer 3 – Decision Output</h2>
        <p className="text-gray-500">Final intelligent verdict generated by TrustLend Core</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Column: Decision Card */}
        <div className="lg:col-span-1 space-y-6">
          <div className={`rounded-3xl p-8 text-white shadow-2xl relative overflow-hidden ${config.color}`}>
            <div className="absolute top-0 right-0 p-4 opacity-10">
              <Icon size={120} />
            </div>
            <div className="relative z-10">
              <Icon size={48} className="mb-6" />
              <h3 className="text-2xl font-bold leading-tight mb-2">{config.text}</h3>
              <p className="opacity-90 text-sm mb-6">{config.subText}</p>
              
              <div className="space-y-4 pt-6 border-t border-white/20">
                <div className="flex justify-between items-center">
                  <span className="text-sm opacity-80">Ref ID:</span>
                  <span className="font-mono font-bold">{application.id.slice(0, 8)}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm opacity-80">Risk Score:</span>
                  <span className="font-bold">{application.analysis.riskScore}/100</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm opacity-80">Fraud Prob:</span>
                  <span className="font-bold">{(application.analysis.fraudProbability).toFixed(1)}%</span>
                </div>
              </div>
            </div>
          </div>

          <button 
            onClick={onReset}
            className="w-full py-4 bg-white text-gray-800 font-bold rounded-2xl border border-gray-200 shadow hover:bg-gray-50 transition-all flex items-center justify-center gap-2"
          >
            <ArrowLeft size={20} /> New Application
          </button>
        </div>

        {/* Right Column: Reasoning & Details */}
        <div className="lg:col-span-2 space-y-8">
          {/* Explainability Module */}
          <div className="bg-white rounded-3xl p-8 shadow-xl border border-gray-100">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 bg-emerald-50 text-emerald-600 rounded-lg">
                <FileText size={24} />
              </div>
              <div>
                <h4 className="text-xl font-bold text-gray-900">Final Answer & AI Reasoning</h4>
                <p className="text-sm text-gray-500">Comprehensive decision justification</p>
              </div>
            </div>
            
            <div className="space-y-6">
              <div className="bg-gray-50 p-6 rounded-2xl italic leading-relaxed text-gray-700 border-l-4 border-emerald-500">
                <p className="font-bold text-emerald-900 not-italic mb-2 uppercase text-xs tracking-widest">Decision Narrative</p>
                {application.analysis.aiExplanation || "Generating detailed reasoning..."}
              </div>

              {/* Final Conclusion Paragraph */}
              <div className="bg-emerald-50/50 p-5 rounded-xl border border-emerald-100/50 text-sm text-emerald-900/80 leading-relaxed shadow-sm">
                  <p className="font-bold text-emerald-900 mb-2 uppercase text-[10px] tracking-widest">Analytic Verdict Summary</p>
                  {isApproved && "The TrustLend AI core concludes that the applicant demonstrates high financial reliability and total documentation consistency. The proposed repayment schedule is well-aligned with the verified net income, and the overall risk profile remains within the bank's strict safety parameters for this asset class."}
                  {isRejected && "The evaluation indicates that while the applicant possesses positive financial traits, the specific combination of the invalid tax documentation and the calculated debt-to-income ratio exceeds the bank's current target solvency model. This decision serves to mitigate long-term risk for both the institution and the applicant."}
                  {isFraud && "Critical forensic analysis has triggered multiple high-priority security alerts. Significant structural inconsistencies were found between the identity documentation and the financial records during the multimodal intake phase. This application has been flagged for immediate escalation to the bank's compliance and internal audit division."}
              </div>

              {(isRejected || isFraud) && application.analysis.possibleImprovements && application.analysis.possibleImprovements.length > 0 && (
                <div className="animate-in slide-in-from-top-4 duration-500">
                  <div className="flex items-center gap-2 mb-3">
                    <Lightbulb className="text-orange-500" size={20} />
                    <h5 className="font-bold text-gray-800">Possible Improvements & Recommendations</h5>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {application.analysis.possibleImprovements.map((imp, idx) => (
                      <div key={idx} className="flex items-start gap-2 bg-orange-50 p-3 rounded-xl border border-orange-100 text-sm text-orange-900">
                        <span className="bg-orange-200 w-5 h-5 flex items-center justify-center rounded-full text-[10px] font-bold shrink-0 mt-0.5">{idx + 1}</span>
                        {imp}
                      </div>
                    ))}
                  </div>
                  <p className="mt-4 text-xs text-gray-400 italic">
                    *Implementing these suggestions does not guarantee future approval but significantly lowers the platform's risk score assessment.
                  </p>
                </div>
              )}
            </div>

            <div className="mt-10 flex gap-3">
              <button className="flex-1 flex items-center justify-center gap-2 py-3 bg-emerald-600 text-white font-bold rounded-xl hover:bg-emerald-700 transition-all">
                <Printer size={18} /> Print Decision Report
              </button>
              <button className="flex items-center justify-center gap-2 px-6 py-3 border border-gray-200 text-gray-600 font-bold rounded-xl hover:bg-gray-50 transition-all">
                <Share2 size={18} /> Send to Manager
              </button>
            </div>
          </div>

          {/* Applicant Summary */}
          <div className="bg-white rounded-3xl p-8 shadow-sm border border-gray-100 grid grid-cols-2 gap-6">
            <div>
              <p className="text-xs text-gray-400 font-bold uppercase tracking-wider mb-1">Applicant</p>
              <p className="text-lg font-bold text-gray-800">{application.applicant.fullName}</p>
              <p className="text-sm text-gray-500">{application.applicant.cinId}</p>
            </div>
            <div>
              <p className="text-xs text-gray-400 font-bold uppercase tracking-wider mb-1">Loan Amount</p>
              <p className="text-lg font-bold text-gray-800">{application.loan.amount.toLocaleString()} TND</p>
              <p className="text-sm text-gray-500">{application.loan.durationMonths} Months</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DecisionView;
